version: '3.1'
services:
  db:
    image: postgres:14.6-alpine
    container_name: postgresql146
    ports: 
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: PUT-YOUR-PASSWORD-HERE # change this with your password
    volumes:
      - postgresql146:/var/lib/postgresql/data
volumes:
  postgresql146: