version: '3.3'
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    restart: on-failure
    privileged: true
    ports:
     - 8080:8080
     - 50000:50000
    container_name: jenkins
    volumes:
        - ./jenkins_data:/var/jenkins_home
        - ./jenkins_docker_certs:/certs/client
        - /var/run/docker.sock:/var/run/docker.sock
